# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/deep-learning-from-scratch-3',
                'doc_host': 'https://oreilly-japan.github.io',
                'git_url': 'https://github.com/oreilly-japan/deep-learning-from-scratch-3',
                'lib_path': 'deep_learning_from_scratch_3'},
  'syms': { 'deep_learning_from_scratch_3.core': { 'deep_learning_from_scratch_3.core.foo': ( 'core.html#foo',
                                                                                              'deep_learning_from_scratch_3/core.py')}}}
